version: '3.6'

services:
  fragematning:
    container_name: fragematning
    depends_on:
      - fragematning-db
    image: ghcr.io/kth-biblioteket/fragematning:${REPO_TYPE}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fragematning.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`${PATHPREFIX}`)"
      - "traefik.http.routers.fragematning.entrypoints=websecure"
      - "traefik.http.routers.fragematning.tls=true"
      - "traefik.http.routers.fragematning.tls.certresolver=myresolver"
    volumes:
      - "/local/docker/fragematning/config_fe.json:/app/frontend/src/config.json:ro"
      - "/local/docker/fragematning/config_be.json:/app/backend/config.json:ro"
    networks:
      - "apps-net"
  
  fragematning-db:
    container_name: fragematning-db
    image: 'mysql:8.0'
    volumes:
      - persistent-fragematning-db:/var/lib/mysql
      - ./dbinit:/docker-entrypoint-initdb.d
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: Europe/Stockholm
    networks:
      - "apps-net"

volumes:
  persistent-fragematning-db:

networks:
  apps-net:
    external: true
